---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-test
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: '>=8.0.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  targetNamespace: default
  values:
    replicas: 1
    service:
      type: ClusterIP
    persistence:
      enabled: false
