---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-additional-config
  namespace: monitoring
data:
  additional-scrape-configs.yaml: |
    - job_name: 'kube-apiserver'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - default
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: kubernetes
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: https
      - target_label: cluster
        replacement: 'k3d-e2e'
      - target_label: job
        replacement: 'kube-apiserver'

    - job_name: 'kubelet'
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - target_label: cluster
        replacement: 'k3d-e2e'
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
